version: 0.2

phases:
  install:
    commands:
      - echo "install phase"
      - docker --version
  pre_build:
    commands:
      - echo "prebuild phase"
  build:
    commands:
      - echo "build phase"
